version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    govet:
      enable:
        - shadow
